export const bollywoodcomedymoviesList = [

    {
        "result": [
            {
                "id": "3486540",
                "mediaType": "MOVIE",
                "mediaSubType": "MOVIE",
                "downloadable": true,
                "languages": [
                    "Hindi"
                ],
                "defaultLanguage": "Hindi",
                "SBU": "X_ERN",
                "multiTrackAudioEnabled": false,
                "shortSynopsis": "Welcome Back is an Indian action comedy film directed by Anees Bazmee and produced by Firoz Nadiadwala, released in 2015. It is a sequel to Welcome. It features an ensemb",
                "fullSynopsis": "Welcome Back is an Indian action comedy film directed by Anees Bazmee and produced by Firoz Nadiadwala, released in 2015. It is a sequel to Welcome. It features an ensemble cast that includes Anil Kapoor, Nana Patekar, John Abraham, Shruti Haasan, Paresh Rawal, Dimple Kapadia and Naseeruddin Shah.",
                "shortTitle": "Welcome Back",
                "fullTitle": "Welcome Back",
                "line1": "Welcome Back",
                "line2": "Hindi ∙ Comedy ∙ U/A 13+",
                "line3": "",
                "showId": "",
                "showName": "",
                "seasonId": "",
                "seasonName": "",
                "season": "",
                "seasonDisplay": "",
                "sampledCount": 0,
                "episode": "",
                "genres": [
                    "Comedy"
                ],
                "subGenre": [],
                "contributors": [
                    "Anil Kapoor",
                    "Nana Patekar",
                    "John Abraham",
                    "Dimple Kapadia",
                    "Shruti Haasan",
                    "Shiney Ahuja",
                    "Paresh Rawal",
                    "Naseeruddin Shah"
                ],
                "characters": [
                    ""
                ],
                "slug": "https://www.jiocinema.com/movies/welcome-back/3486540/watch",
                "assetRef": {},
                "telecastDate": "20160806",
                "releaseYear": 2015,
                "contentDescriptor": "",
                "contentSubject": "",
                "age": "U/A 13+",
                "ageNumeric": 13,
                "ageNemonic": "13+",
                "ageDisplay": "U/A 13+",
                "name": "Welcome Back",
                "duration": 8938,
                "durationFormatted": "2h 29m",
                "seo": {
                    "page": "Welcome Back",
                    "title": "Welcome Back (2015) Hindi Movie: Watch Full HD Movie Online On JioCinema",
                    "urlStructure": "https://www.jiocinema.com/movies/welcome-back/3486540/watch",
                    "urlStructureNew": "https://www.jiocinema.com/movies/welcome-back/3486540/watch",
                    "description": "Welcome Back (2015) Is A Comedy Hindi Film Starring Anil Kapoor,Nana Patekar,John Abraham,Dimple Kapadia,Shruti Haasan,Shiney Ahuja,Paresh Rawal,Naseeruddin Shah In The Lead Roles, Directed By Anees Bazmee. Watch Now Or Download To Watch Later!",
                    "keywords": [
                        "Welcome Back",
                        "Welcome Back 2015 Online",
                        "Watch Hindi Movie Welcome Back online",
                        "Watch Welcome Back 2015",
                        "Welcome Back HD Streaming Online",
                        "Welcome Back videos",
                        "ErosNow"
                    ],
                    "ogTitle": "Welcome Back (2015) Hindi Movie: Watch Full HD Movie Online On JioCinema",
                    "ogDescription": "Welcome Back (2015) Is A Comedy Hindi Film Starring Anil Kapoor,Nana Patekar,John Abraham,Dimple Kapadia,Shruti Haasan,Shiney Ahuja,Paresh Rawal,Naseeruddin Shah In The Lead Roles, Directed By Anees Bazmee. Watch Now Or Download To Watch Later!",
                    "ogImage": "https://v3img.voot.com/v3Storage/assets/welcome-back-3x4-1713975728023.jpg",
                    "imgTitle": "Welcome Back",
                    "imgAltTags": "Watch Welcome Back Online"
                },
                "introStart": 5,
                "introEnd": 241,
                "recapStart": 0,
                "recapEnd": 0,
                "creditStart": 8766,
                "creditEnd": 8932,
                "deeplinkUrl": "jiovootviacom18://jiovoot/detail/3486540",
                "shareUrl": "https://go.jc.fm/fRhd/jijbiub7",
                "shareUrlTabs": {},
                "shareUrlMessage": "Enjoy Welcome Back on JioCinema. Click https://go.jc.fm/fRhd/jijbiub7 now!",
                "jioMediaId": "3486540",
                "isDAIEnabled": false,
                "daiAssetKey": "",
                "isDVREnabled": false,
                "isHLSEnabled": false,
                "releaseDate": 1470441600,
                "uploadTime": 1470441600,
                "assetMarketType": "STANDARD",
                "showMarketType": "STANDARD",
                "assetBusinessType": [
                    "Free"
                ]
            },
            {
                "id": "3487646",
                "mediaType": "MOVIE",
                "mediaSubType": "MOVIE",
                "downloadable": true,
                "languages": [
                    "Hindi"
                ],
                "defaultLanguage": "Hindi",
                "SBU": "X_ERN",
                "multiTrackAudioEnabled": false,
                "shortSynopsis": "Tanu and Manu's marriage collapses. What happens when Manu meets Tanu's lookalike Kusum - and when Tanu returns?",
                "fullSynopsis": "Tanu and Manu's marriage collapses. What happens when Manu meets Tanu's lookalike Kusum - and when Tanu returns?",
                "shortTitle": "Tanu Weds Manu Returns",
                "fullTitle": "Tanu Weds Manu Returns",
                "line1": "Tanu Weds Manu Returns",
                "line2": "Hindi ∙ Romance ∙ U/A 13+",
                "line3": "",
                "showId": "",
                "showName": "",
                "seasonId": "",
                "seasonName": "",
                "season": "",
                "seasonDisplay": "",
                "sampledCount": 0,
                "episode": "",
                "genres": [
                    "Romance"
                ],
                "subGenre": [
                    "Comedy"
                ],
                "contributors": [
                    "Madhavan",
                    "Kangana Ranaut",
                    "Jimmy Shergill"
                ],
                "characters": [
                    ""
                ],
                "slug": "https://www.jiocinema.com/movies/tanu-weds-manu-returns/3487646/watch",
                "assetRef": {},
                "telecastDate": "20160730",
                "releaseYear": 2015,
                "contentDescriptor": "Comic mischief, Family viewing, Drama",
                "contentSubject": "",
                "age": "U/A 13+",
                "ageNumeric": 13,
                "ageNemonic": "13+",
                "ageDisplay": "U/A 13+",
                "name": "Tanu Weds Manu Returns",
                "duration": 7638,
                "durationFormatted": "2h 7m",
                "seo": {
                    "page": "Tanu Weds Manu Returns",
                    "title": "Tanu Weds Manu Returns (2015) Hindi Movie: Watch Full HD Movie Online On JioCinema",
                    "urlStructure": "https://www.jiocinema.com/movies/tanu-weds-manu-returns/3487646/watch",
                    "urlStructureNew": "https://www.jiocinema.com/movies/tanu-weds-manu-returns/3487646/watch",
                    "description": "Tanu Weds Manu Returns (2015) Is A Romance Hindi Film Starring Madhavan,Kangana Ranaut,Jimmy Shergill In The Lead Roles, Directed By Aanand Rai. Watch Now Or Download To Watch Later!",
                    "keywords": [
                        "Tanu Weds Manu Returns",
                        "Tanu Weds Manu Returns 2015 Online",
                        "Watch Hindi Movie Tanu Weds Manu Returns online",
                        "Watch Tanu Weds Manu Returns 2015",
                        "Tanu Weds Manu Returns HD Streaming Online",
                        "Tanu Weds Manu Returns videos",
                        ""
                    ],
                    "ogTitle": "Tanu Weds Manu Returns (2015) Hindi Movie: Watch Full HD Movie Online On JioCinema",
                    "ogDescription": "Tanu Weds Manu Returns (2015) Is A Romance Hindi Film Starring Madhavan,Kangana Ranaut,Jimmy Shergill In The Lead Roles, Directed By Aanand Rai. Watch Now Or Download To Watch Later!",
                    "ogImage": "https://v3img.voot.com/v3Storage/assets/tanu-weds-manu-returns-3x4-1707810871757.jpg",
                    "imgTitle": "Tanu Weds Manu Returns",
                    "imgAltTags": "Watch Tanu Weds Manu Returns Online"
                }
            },
            {
                "id": "3837010",
                "mediaType": "MOVIE",
                "mediaSubType": "MOVIE",
                "downloadable": true,
                "languages": [
                    "Hindi"
                ],
                "defaultLanguage": "Hindi",
                "SBU": "VMP",
                "multiTrackAudioEnabled": false,
                "shortSynopsis": "Manu the epitome of the word staid is introduced to Tanu who is anything but. Add to the mix a boyfriend who Tanu intends to elope with and you have a true Bollywood Rom ",
                "fullSynopsis": "Manu the epitome of the word staid is introduced to Tanu who is anything but. Add to the mix a boyfriend who Tanu intends to elope with and you have a true Bollywood Rom Com. Will Tanu indeed marry Manu?",
                "shortTitle": "Tanu Weds Manu",
                "fullTitle": "Tanu Weds Manu",
                "line1": "Tanu Weds Manu",
                "line2": "Hindi ∙ Romance ∙ U/A 13+",
                "line3": "",
                "showId": "",
                "showName": "",
                "seasonId": "",
                "seasonName": "",
                "season": "",
                "seasonDisplay": "",
                "sampledCount": 0,
                "episode": "",
                "genres": [
                    "Romance"
                ],
                "subGenre": [],
                "contributors": [
                    "Kangana Ranaut",
                    "Jimmy Shergill",
                    "Ravi Kishan",
                    "Dipti Mishra",
                    "Swara Bhaskar",
                    "K K Raina",
                    "Rajendra Gupta",
                    "Navni Parihar",
                    "Neha Kaul",
                    "Archana Shukla",
                    "R.Madhavan",
                    "Deepak Dobriyal",
                    "Eijaz Khan"
                ],
                "characters": [
                    "Tanuja 'Tanu' Trivedi",
                    "Raja Awasthi",
                    "Raja's friend",
                    "Mrs. Sharma",
                    "Payal",
                    "Jassi's bride",
                    "Mr. Sharma",
                    "Mr. Trivedi",
                    "Mrs. Trivedi",
                    "Ayushi",
                    "Raja's sister",
                    "Bulbul Sas",
                    "Manoj 'Mannu' Sharma",
                    "Pappi",
                    "Mannu's friend",
                    "Jassi",
                    "Mannu's friend"
                ],
                "slug": "https://www.jiocinema.com/movies/tanu-weds-manu/3837010/watch",
                "assetRef": {},
                "telecastDate": "20231015",
                "releaseYear": 2011,
                "contentDescriptor": "Comic mischief, Family viewing, Drama",
                "contentSubject": "",
                "age": "U/A 13+",
                "ageNumeric": 13,
                "ageNemonic": "13+",
                "ageDisplay": "U/A 13+",
                "name": "Tanu Weds Manu",
                "duration": 6862,
                "durationFormatted": "1h 54m",
                "seo": {
                    "page": "Tanu Weds Manu",
                    "title": "Tanu Weds Manu (2011) Hindi Movie: Watch Full HD Movie Online On JioCinema",
                    "urlStructure": "https://www.jiocinema.com/movies/tanu-weds-manu/3837010/watch",
                    "urlStructureNew": "https://www.jiocinema.com/movies/tanu-weds-manu/3837010/watch",
                    "description": "Tanu Weds Manu (2011) Is A Romance Hindi Film Starring Kangana Ranaut,Jimmy Shergill,Ravi Kishan,Dipti Mishra,Swara Bhaskar,K K Raina,Rajendra Gupta,Navni Parihar,Neha Kaul,Archana Shukla,R.Madhavan,Deepak Dobriyal,Eijaz Khan In The Lead Roles, Directed By . Watch Now Or Download To Watch Later!",
                    "keywords": [
                        "Tanu Weds Manu",
                        "Tanu Weds Manu 2011 Online",
                        "Watch Hindi Movie Tanu Weds Manu online",
                        "Watch Tanu Weds Manu 2011",
                        "Tanu Weds Manu HD Streaming Online",
                        "Tanu Weds Manu videos",
                        "Drama",
                        "Action",
                        "Love Triangle",
                        "Marriage",
                        "Sleeping Pills",
                        "Boyfriend",
                        "Comedy",
                        "Heart-Touching",
                        "Sentimental",
                        "Cupid",
                        "Wedding",
                        "Sacrifice",
                        "Villain"
                    ],
                    "ogTitle": "Tanu Weds Manu (2011) Hindi Movie: Watch Full HD Movie Online On JioCinema",
                    "ogDescription": "Tanu Weds Manu (2011) Is A Romance Hindi Film Starring Kangana Ranaut,Jimmy Shergill,Ravi Kishan,Dipti Mishra,Swara Bhaskar,K K Raina,Rajendra Gupta,Navni Parihar,Neha Kaul,Archana Shukla,R.Madhavan,Deepak Dobriyal,Eijaz Khan In The Lead Roles, Directed By . Watch Now Or Download To Watch Later!",
                    "ogImage": "https://v3img.voot.com/v3Storage/assets/0_30o86qz6_1492682065_p-1697540246179.jpg",
                    "imgTitle": "Tanu Weds Manu",
                    "imgAltTags": "Watch Tanu Weds Manu Online"
                },
                "introStart": 131,
                "introEnd": 158,
                "recapStart": 0,
                "recapEnd": 0,
                "creditStart": 6684,
                "creditEnd": 6861,
                "deeplinkUrl": "jiovootviacom18://jiovoot/detail/3837010",
                "shareUrl": "https://go.jc.fm/fRhd/3gacokk0",
                "shareUrlTabs": {},
                "shareUrlMessage": "Enjoy Tanu Weds Manu on JioCinema. Click https://go.jc.fm/fRhd/3gacokk0 now!",
                "jioMediaId": "3837010",
                "isDAIEnabled": false,
                "daiAssetKey": "",
                "isDVREnabled": false,
                "isHLSEnabled": false,
                "releaseDate": 1604386200,
                "uploadTime": 1604386200,
                "assetMarketType": "STANDARD",
                "showMarketType": "STANDARD",
                "assetBusinessType": [
                    "Free"
                ]
            },
            {
                "id": "3489693",
                "mediaType": "MOVIE",
                "mediaSubType": "MOVIE",
                "downloadable": true,
                "languages": [
                    "Hindi"
                ],
                "defaultLanguage": "Hindi",
                "SBU": "X_ERN",
                "multiTrackAudioEnabled": false,
                "shortSynopsis": "A man is brought in by an infertility doctor to supply him with his sperm, where he becomes the biggest sperm donor for his clinic.",
                "fullSynopsis": "A man is brought in by an infertility doctor to supply him with his sperm, where he becomes the biggest sperm donor for his clinic.",
                "shortTitle": "Vicky Donor",
                "fullTitle": "Vicky Donor",
                "line1": "Vicky Donor",
                "line2": "Hindi ∙ Comedy ∙ U/A 13+",
                "line3": "",
                "showId": "",
                "showName": "",
                "seasonId": "",
                "seasonName": "",
                "season": "",
                "seasonDisplay": "",
                "sampledCount": 0,
                "episode": "",
                "genres": [
                    "Comedy"
                ],
                "subGenre": [],
                "contributors": [
                    "Ayushmann Khurrana",
                    "Yami Gautam"
                ],
                "characters": [
                    ""
                ],
                "slug": "https://www.jiocinema.com/movies/vicky-donor/3489693/watch",
                "assetRef": {},
                "telecastDate": "20170101",
                "releaseYear": 2012,
                "contentDescriptor": "",
                "contentSubject": "",
                "age": "U/A 13+",
                "ageNumeric": 13,
                "ageNemonic": "13+",
                "ageDisplay": "U/A 13+",
                "name": "Vicky Donor",
                "duration": 7507,
                "durationFormatted": "2h 5m",
                "seo": {
                    "page": "Vicky Donor",
                    "title": "Vicky Donor (2012) Hindi Movie: Watch Full HD Movie Online On JioCinema",
                    "urlStructure": "https://www.jiocinema.com/movies/vicky-donor/3489693/watch",
                    "urlStructureNew": "https://www.jiocinema.com/movies/vicky-donor/3489693/watch",
                    "description": "Vicky Donor (2012) Is A Comedy Hindi Film Starring Ayushmann Khurrana,Yami Gautam In The Lead Roles, Directed By Shoojit Sircar. Watch Now Or Download To Watch Later!",
                    "keywords": [
                        "Vicky Donor",
                        "Vicky Donor 2012 Online",
                        "Watch Hindi Movie Vicky Donor online",
                        "Watch Vicky Donor 2012",
                        "Vicky Donor HD Streaming Online",
                        "Vicky Donor videos",
                        ""
                    ],
                    "ogTitle": "Vicky Donor (2012) Hindi Movie: Watch Full HD Movie Online On JioCinema",
                    "ogDescription": "Vicky Donor (2012) Is A Comedy Hindi Film Starring Ayushmann Khurrana,Yami Gautam In The Lead Roles, Directed By Shoojit Sircar. Watch Now Or Download To Watch Later!",
                    "ogImage": "https://v3img.voot.com/v3Storage/assets/vicky-1674034436622.jpg",
                    "imgTitle": "Vicky Donor",
                    "imgAltTags": "Watch Vicky Donor Online"
                }
            },
            {
                "id": "3502656",
                "mediaType": "MOVIE",
                "mediaSubType": "MOVIE",
                "downloadable": true,
                "languages": [
                    "Hindi"
                ],
                "defaultLanguage": "Hindi",
                "SBU": "CCP",
                "multiTrackAudioEnabled": false,
                "shortSynopsis": "Prem's helping nature benefits him, and he befriends a kind-hearted girl named Jenny and falls in love with her. However, he learns that Jenny loves another person named ",
                "fullSynopsis": "Prem's helping nature benefits him, and he befriends a kind-hearted girl named Jenny and falls in love with her. However, he learns that Jenny loves another person named Rahul and Prem decides to help them get married. Will Jenny marry Rahul?",
                "shortTitle": "Ajab Prem Ki Ghazab Kahani",
                "fullTitle": "Ajab Prem Ki Ghazab Kahani",
                "line1": "Ajab Prem Ki Ghazab Kahani",
                "line2": "Hindi ∙ Comedy, Romance ∙ U/A 13+",
                "line3": "",
                "showId": "",
                "showName": "",
                "seasonId": "",
                "seasonName": "",
                "season": "",
                "seasonDisplay": "",
                "sampledCount": 0,
                "episode": "",
                "genres": [
                    "Comedy",
                    "Romance"
                ],
                "subGenre": [],
                "contributors": [
                    "Ranbir Kapoor",
                    "Katrina Kaif"
                ],
                "characters": [
                    ""
                ],
                "slug": "https://www.jiocinema.com/movies/ajab-prem-ki-ghazab-kahani/3502656/watch",
                "assetRef": {},
                "telecastDate": "20221031",
                "releaseYear": 2009,
                "contentDescriptor": "Comic mischief, Mild language",
                "contentSubject": "",
                "age": "U/A 13+",
                "ageNumeric": 13,
                "ageNemonic": "13+",
                "ageDisplay": "U/A 13+",
                "name": "Ajab Prem Ki Ghazab Kahani",
                "duration": 8663,
                "durationFormatted": "2h 24m",
                "seo": {
                    "page": "Ajab Prem Ki Ghazab Kahani",
                    "title": "Ajab Prem Ki Ghazab Kahani (2009) Hindi Movie: Watch Full HD Movie Online On JioCinema",
                    "urlStructure": "https://www.jiocinema.com/movies/ajab-prem-ki-ghazab-kahani/3502656/watch",
                    "urlStructureNew": "https://www.jiocinema.com/movies/ajab-prem-ki-ghazab-kahani/3502656/watch",
                    "description": "Ajab Prem Ki Ghazab Kahani (2009) Is A Comedy Hindi Film Starring Ranbir Kapoor,Katrina Kaif In The Lead Roles, Directed By Rajkumar Santoshi. Watch Now Or Download To Watch Later!",
                    "keywords": [
                        "Ajab Prem Ki Ghazab Kahani",
                        "Ajab Prem Ki Ghazab Kahani 2009 Online",
                        "Watch Hindi Movie Ajab Prem Ki Ghazab Kahani online",
                        "Watch Ajab Prem Ki Ghazab Kahani 2009",
                        "Ajab Prem Ki Ghazab Kahani HD Streaming Online",
                        "Ajab Prem Ki Ghazab Kahani videos",
                        "Voot",
                        "Movies",
                        "Voot movies",
                        "New movies on Voot",
                        "Ajab Prem Ki Ghazab Kahani",
                        "Love story",
                        "Romantic Comedy Movie",
                        "Romcom movie",
                        "Hindi movies on Voot",
                        "Prem",
                        "Jenny",
                        "Rahul",
                        "Ranbir Kapoor",
                        "Katrina Kaif"
                    ],
                    "ogTitle": "Ajab Prem Ki Ghazab Kahani (2009) Hindi Movie: Watch Full HD Movie Online On JioCinema",
                    "ogDescription": "Ajab Prem Ki Ghazab Kahani (2009) Is A Comedy Hindi Film Starring Ranbir Kapoor,Katrina Kaif In The Lead Roles, Directed By Rajkumar Santoshi. Watch Now Or Download To Watch Later!",
                    "ogImage": "https://v3img.voot.com/v3Storage/assets/ajab-3x4-1698557986984.png",
                    "imgTitle": "Ajab Prem Ki Ghazab Kahani",
                    "imgAltTags": "Watch Ajab Prem Ki Ghazab Kahani Online"
                }
            },
            {
                "id": "3489698",
                "mediaType": "MOVIE",
                "mediaSubType": "MOVIE",
                "downloadable": true,
                "languages": [
                    "Hindi"
                ],
                "defaultLanguage": "Hindi",
                "SBU": "X_ERN",
                "multiTrackAudioEnabled": false,
                "shortSynopsis": "Two friends lose their jobs, then part bitterly after they get exposed as male escorts.",
                "fullSynopsis": "Two friends lose their jobs, then part bitterly after they get exposed as male escorts.",
                "shortTitle": "Desi Boyz",
                "fullTitle": "Desi Boyz",
                "line1": "Desi Boyz",
                "line2": "Hindi ∙ Comedy ∙ A",
                "line3": "",
                "showId": "",
                "showName": "",
                "seasonId": "",
                "seasonName": "",
                "season": "",
                "seasonDisplay": "",
                "sampledCount": 0,
                "episode": "",
                "genres": [
                    "Comedy"
                ],
                "subGenre": [],
                "contributors": [
                    "Akshay Kumar",
                    "John Abraham",
                    "Deepika Padukone",
                    "Chitrangada Singh"
                ],
                "characters": [
                    ""
                ],
                "slug": "https://www.jiocinema.com/movies/desi-boyz/3489698/watch",
                "assetRef": {},
                "telecastDate": "20170101",
                "releaseYear": 2011,
                "contentDescriptor": "Mild sexual references, Moderate language",
                "contentSubject": "",
                "age": "A",
                "ageNumeric": 18,
                "ageNemonic": "A",
                "ageDisplay": "A",
                "name": "Desi Boyz",
                "duration": 7299,
                "durationFormatted": "2h 2m",
                "seo": {
                    "page": "Desi Boyz",
                    "title": "Desi Boyz (2011) Hindi Movie: Watch Full HD Movie Online On JioCinema",
                    "urlStructure": "https://www.jiocinema.com/movies/desi-boyz/3489698/watch",
                    "urlStructureNew": "https://www.jiocinema.com/movies/desi-boyz/3489698/watch",
                    "description": "Desi Boyz (2011) Is A Comedy Hindi Film Starring Akshay Kumar,John Abraham,Deepika Padukone,Chitrangada Singh In The Lead Roles, Directed By Rohit Dhawan. Watch Now Or Download To Watch Later!",
                    "keywords": [
                        "Desi Boyz",
                        "Desi Boyz 2011 Online",
                        "Watch Hindi Movie Desi Boyz online",
                        "Watch Desi Boyz 2011",
                        "Desi Boyz HD Streaming Online",
                        "Desi Boyz videos",
                        ""
                    ],
                    "ogTitle": "Desi Boyz (2011) Hindi Movie: Watch Full HD Movie Online On JioCinema",
                    "ogDescription": "Desi Boyz (2011) Is A Comedy Hindi Film Starring Akshay Kumar,John Abraham,Deepika Padukone,Chitrangada Singh In The Lead Roles, Directed By Rohit Dhawan. Watch Now Or Download To Watch Later!",
                    "ogImage": "https://v3img.voot.com/v3Storage/assets/3x4-1710402427368.jpg",
                    "imgTitle": "Desi Boyz",
                    "imgAltTags": "Watch Desi Boyz Online"
                },
                "introStart": 2,
                "introEnd": 87,
                "recapStart": 0,
                "recapEnd": 0,
                "creditStart": 7099,
                "creditEnd": 7299,
                "deeplinkUrl": "jiovootviacom18://jiovoot/detail/3489698",
                "shareUrl": "https://go.jc.fm/fRhd/aklhlr2x",
                "shareUrlTabs": {},
                "shareUrlMessage": "Enjoy Desi Boyz on JioCinema. Click https://go.jc.fm/fRhd/aklhlr2x now!",
                "jioMediaId": "3489698",
                "isDAIEnabled": false,
                "daiAssetKey": "",
                "isDVREnabled": false,
                "isHLSEnabled": false,
                "releaseDate": 1483228800,
                "uploadTime": 1483228800,
                "assetMarketType": "STANDARD",
                "showMarketType": "STANDARD",
                "assetBusinessType": [
                    "Free"
                ]
            },
            {
                "id": "3488973",
                "mediaType": "MOVIE",
                "mediaSubType": "MOVIE",
                "downloadable": true,
                "languages": [
                    "Hindi"
                ],
                "defaultLanguage": "Hindi",
                "SBU": "X_ERN",
                "multiTrackAudioEnabled": false,
                "shortSynopsis": "After fleeing an arranged marriage, a feisty Indian woman finds herself stranded in Pakistan where the ex-governor's son helps reunite her with her boyfriend.",
                "fullSynopsis": "After fleeing an arranged marriage, a feisty Indian woman finds herself stranded in Pakistan where the ex-governor's son helps reunite her with her boyfriend.",
                "shortTitle": "Happy Bhag Jayegi",
                "fullTitle": "Happy Bhag Jayegi",
                "line1": "Happy Bhag Jayegi",
                "line2": "Hindi ∙ Comedy ∙ U/A 13+",
                "line3": "",
                "showId": "",
                "showName": "",
                "seasonId": "",
                "seasonName": "",
                "season": "",
                "seasonDisplay": "",
                "sampledCount": 0,
                "episode": "",
                "genres": [
                    "Comedy"
                ],
                "subGenre": [],
                "contributors": [
                    "Diana Penty",
                    "Abhay Deol",
                    "Jimmy Shergill"
                ],
                "characters": [
                    ""
                ],
                "slug": "https://www.jiocinema.com/movies/happy-bhag-jayegi/3488973/watch",
                "assetRef": {},
                "telecastDate": "20161017",
                "releaseYear": 2016,
                "contentDescriptor": "",
                "contentSubject": "",
                "age": "U/A 13+",
                "ageNumeric": 13,
                "ageNemonic": "13+",
                "ageDisplay": "U/A 13+",
                "name": "Happy Bhag Jayegi",
                "duration": 7552,
                "durationFormatted": "2h 6m",
                "seo": {
                    "page": "Happy Bhag Jayegi",
                    "title": "Happy Bhag Jayegi (2016) Hindi Movie: Watch Full HD Movie Online On JioCinema",
                    "urlStructure": "https://www.jiocinema.com/movies/happy-bhag-jayegi/3488973/watch",
                    "urlStructureNew": "https://www.jiocinema.com/movies/happy-bhag-jayegi/3488973/watch",
                    "description": "Happy Bhag Jayegi (2016) Is A Comedy Hindi Film Starring Diana Penty,Abhay Deol,Jimmy Shergill In The Lead Roles, Directed By Mudassar Aziz. Watch Now Or Download To Watch Later!",
                    "keywords": [
                        "Happy Bhag Jayegi",
                        "Happy Bhag Jayegi 2016 Online",
                        "Watch Hindi Movie Happy Bhag Jayegi online",
                        "Watch Happy Bhag Jayegi 2016",
                        "Happy Bhag Jayegi HD Streaming Online",
                        "Happy Bhag Jayegi videos",
                        ""
                    ],
                    "ogTitle": "Happy Bhag Jayegi (2016) Hindi Movie: Watch Full HD Movie Online On JioCinema",
                    "ogDescription": "Happy Bhag Jayegi (2016) Is A Comedy Hindi Film Starring Diana Penty,Abhay Deol,Jimmy Shergill In The Lead Roles, Directed By Mudassar Aziz. Watch Now Or Download To Watch Later!",
                    "ogImage": "https://v3img.voot.com/v3Storage/assets/happy-bhag-jayegi-3x4-1713983301381.jpg",
                    "imgTitle": "Happy Bhag Jayegi",
                    "imgAltTags": "Watch Happy Bhag Jayegi Online"
                },
                "introStart": 2,
                "introEnd": 81,
                "recapStart": 0,
                "recapEnd": 0,
                "creditStart": 7364,
                "creditEnd": 7552,
                "deeplinkUrl": "jiovootviacom18://jiovoot/detail/3488973",
                "shareUrl": "https://go.jc.fm/fRhd/5ya3fsa3",
                "shareUrlTabs": {},
                "shareUrlMessage": "Enjoy Happy Bhag Jayegi on JioCinema. Click https://go.jc.fm/fRhd/5ya3fsa3 now!",
                "jioMediaId": "3488973",
                "isDAIEnabled": false,
                "daiAssetKey": "",
                "isDVREnabled": false,
                "isHLSEnabled": false,
                "releaseDate": 1476662400,
                "uploadTime": 1476662400,
                "assetMarketType": "STANDARD",
                "showMarketType": "STANDARD",
                "assetBusinessType": [
                    "Free"
                ]
            },
            {
                "id": "3492008",
                "mediaType": "MOVIE",
                "mediaSubType": "MOVIE",
                "downloadable": true,
                "languages": [
                    "Hindi"
                ],
                "defaultLanguage": "Hindi",
                "SBU": "X_ERN",
                "multiTrackAudioEnabled": false,
                "shortSynopsis": "Yudi (Saif Ali Khan) is a one-book wonder and someone who is not allergic to love, but the baggage associated with it. He gets into a string of bad relationships, includi",
                "fullSynopsis": "Yudi (Saif Ali Khan) is a one-book wonder and someone who is not allergic to love, but the baggage associated with it. He gets into a string of bad relationships, including one with the borderline-crazy Vishaka (Kalki Koechlin), who is so in love with him that she tracks all his movements. The only people who bring him relief are his former girlfriend Divya (Preity Zinta) and his best friend Montu (Ranveer Shorey). Yudi blows up all his earnings from the book; to add insult to injury, his publishers commission the gorgeous Aanchal Reddy (Ileana D'cruz), whose romantic novels sell like hot cakes. He is then offered to write a script for Armaanji (Govinda), an actor who wants to reinvent himself. Hoping to get a hold of Aanchal s success formula, Yudi decides to befriend her. Aanchal, who has no idea about Yudi s ulterior motives, agrees to be with him but not fall in love with him. How will Yudi struggle with the feelings he develops for Aanchal? And how will Vishaka react to it? Will he manage to stage a comeback with Armaanji s film and get his life in order?",
                "shortTitle": "Happy Ending",
                "fullTitle": "Happy Ending",
                "line1": "Happy Ending",
                "line2": "Hindi ∙ Comedy ∙ U/A 13+",
                "line3": "",
                "showId": "",
                "showName": "",
                "seasonId": "",
                "seasonName": "",
                "season": "",
                "seasonDisplay": "",
                "sampledCount": 0,
                "episode": "",
                "genres": [
                    "Comedy"
                ],
                "subGenre": [],
                "contributors": [
                    "Saif Ali Khan",
                    "Ileana D'Cruz",
                    "Kalki Koechlin",
                    "Govinda",
                    "Ranvir Shorey"
                ],
                "characters": [
                    ""
                ],
                "slug": "https://www.jiocinema.com/movies/happy-ending/3492008/watch",
                "assetRef": {},
                "telecastDate": "20160907",
                "releaseYear": 2014,
                "contentDescriptor": "",
                "contentSubject": "",
                "age": "U/A 13+",
                "ageNumeric": 13,
                "ageNemonic": "13+",
                "ageDisplay": "U/A 13+",
                "name": "Happy Ending",
                "duration": 8066,
                "durationFormatted": "2h 14m",
                "seo": {
                    "page": "Happy Ending",
                    "title": "Happy Ending (2014) Hindi Movie: Watch Full HD Movie Online On JioCinema",
                    "urlStructure": "https://www.jiocinema.com/movies/happy-ending/3492008/watch",
                    "urlStructureNew": "https://www.jiocinema.com/movies/happy-ending/3492008/watch",
                    "description": "Happy Ending (2014) Is A Comedy Hindi Film Starring Saif Ali Khan,Ileana D'Cruz,Kalki Koechlin,Govinda,Ranvir Shorey In The Lead Roles, Directed By Raj & DK. Watch Now Or Download To Watch Later!",
                    "keywords": [
                        "Happy Ending",
                        "Happy Ending 2014 Online",
                        "Watch Hindi Movie Happy Ending online",
                        "Watch Happy Ending 2014",
                        "Happy Ending HD Streaming Online",
                        "Happy Ending videos",
                        "Happy Ending Movie"
                    ],
                    "ogTitle": "Happy Ending (2014) Hindi Movie: Watch Full HD Movie Online On JioCinema",
                    "ogDescription": "Happy Ending (2014) Is A Comedy Hindi Film Starring Saif Ali Khan,Ileana D'Cruz,Kalki Koechlin,Govinda,Ranvir Shorey In The Lead Roles, Directed By Raj & DK. Watch Now Or Download To Watch Later!",
                    "ogImage": "https://v3img.voot.com/v3Storage/assets/happy-ending-1674134376831.jpg",
                    "imgTitle": "Happy Ending",
                    "imgAltTags": "Watch Happy Ending Online"
                },
                "introStart": 2,
                "introEnd": 71,
                "recapStart": 0,
                "recapEnd": 0,
                "creditStart": 7776,
                "creditEnd": 8066,
                "deeplinkUrl": "jiovootviacom18://jiovoot/detail/3492008",
                "shareUrl": "https://go.jc.fm/fRhd/s1lau2fn",
                "shareUrlTabs": {},
                "shareUrlMessage": "Enjoy Happy Ending on JioCinema. Click https://go.jc.fm/fRhd/s1lau2fn now!",
                "jioMediaId": "3492008",
                "isDAIEnabled": false,
                "daiAssetKey": "",
                "isDVREnabled": false,
                "isHLSEnabled": false,
                "releaseDate": 1473206400,
                "uploadTime": 1473206400,
                "assetMarketType": "STANDARD",
                "showMarketType": "STANDARD",
                "assetBusinessType": [
                    "Free"
                ]
            },
            {
                "id": "3486606",
                "mediaType": "MOVIE",
                "mediaSubType": "MOVIE",
                "downloadable": true,
                "languages": [
                    "Hindi"
                ],
                "defaultLanguage": "Hindi",
                "SBU": "X_ERN",
                "multiTrackAudioEnabled": false,
                "shortSynopsis": "A love triangle between a guy and two girls, who are best friends but the complete opposite of one another.",
                "fullSynopsis": "A love triangle between a guy and two girls, who are best friends but the complete opposite of one another.",
                "shortTitle": "Cocktail",
                "fullTitle": "Cocktail",
                "line1": "Cocktail",
                "line2": "Hindi ∙ Romance ∙ U/A 13+",
                "line3": "",
                "showId": "",
                "showName": "",
                "seasonId": "",
                "seasonName": "",
                "season": "",
                "seasonDisplay": "",
                "sampledCount": 0,
                "episode": "",
                "genres": [
                    "Romance"
                ],
                "subGenre": [
                    "Comedy"
                ],
                "contributors": [
                    "Saif Ali Khan",
                    " Deepika Padukone",
                    " Diana Penty",
                    " Dimple Kapadia",
                    " Randeep Hooda"
                ],
                "characters": [
                    ""
                ],
                "slug": "https://www.jiocinema.com/movies/cocktail/3486606/watch",
                "assetRef": {},
                "telecastDate": "20161109",
                "releaseYear": 2012,
                "contentDescriptor": "",
                "contentSubject": "",
                "age": "U/A 13+",
                "ageNumeric": 13,
                "ageNemonic": "13+",
                "ageDisplay": "U/A 13+",
                "name": "Cocktail",
                "duration": 8673,
                "durationFormatted": "2h 25m",
                "seo": {
                    "page": "Cocktail",
                    "title": "Cocktail (2012) Hindi Movie: Watch Full HD Movie Online On JioCinema",
                    "urlStructure": "https://www.jiocinema.com/movies/cocktail/3486606/watch",
                    "urlStructureNew": "https://www.jiocinema.com/movies/cocktail/3486606/watch",
                    "description": "Cocktail (2012) Is A Romance Hindi Film Starring Saif Ali Khan, Deepika Padukone, Diana Penty, Dimple Kapadia, Randeep Hooda In The Lead Roles, Directed By Homi Adajania. Watch Now Or Download To Watch Later!",
                    "keywords": [
                        "Cocktail",
                        "Cocktail 2012 Online",
                        "Watch Hindi Movie Cocktail online",
                        "Watch Cocktail 2012",
                        "Cocktail HD Streaming Online",
                        "Cocktail videos",
                        ""
                    ],
                    "ogTitle": "Cocktail (2012) Hindi Movie: Watch Full HD Movie Online On JioCinema",
                    "ogDescription": "Cocktail (2012) Is A Romance Hindi Film Starring Saif Ali Khan, Deepika Padukone, Diana Penty, Dimple Kapadia, Randeep Hooda In The Lead Roles, Directed By Homi Adajania. Watch Now Or Download To Watch Later!",
                    "ogImage": "https://v3img.voot.com/v3Storage/assets/cocktail-1676037595210-1716386767719.jpg",
                    "imgTitle": "Cocktail",
                    "imgAltTags": "Watch Cocktail Online"
                }
            },
            {
                "id": "3754021",
                "mediaType": "MOVIE",
                "mediaSubType": "MOVIE",
                "downloadable": true,
                "languages": [
                    "Hindi"
                ],
                "defaultLanguage": "Hindi",
                "SBU": "JCM",
                "multiTrackAudioEnabled": false,
                "shortSynopsis": "Bhediya is a story of a man named Bhaskar who gets bitten by a wolf in the forests of Arunachal. While Bhaskar transforms into a shape-shifting werewolf, he and his frien",
                "fullSynopsis": "Bhediya is a story of a man named Bhaskar who gets bitten by a wolf in the forests of Arunachal. While Bhaskar transforms into a shape-shifting werewolf, he and his friends look for answers amid many twists, turns and laughter.",
                "shortTitle": "Bhediya",
                "fullTitle": "Bhediya",
                "line1": "Bhediya",
                "line2": "हि, ಕ, +5 more ∙ Comedy ∙ U/A 13+",
                "line3": "",
                "showId": "",
                "showName": "",
                "seasonId": "",
                "seasonName": "",
                "season": "",
                "seasonDisplay": "",
                "sampledCount": 0,
                "episode": "",
                "genres": [
                    "Comedy"
                ],
                "subGenre": [],
                "contributors": [
                    "Varun Dhawan",
                    "Kriti Sanon",
                    "Deepak Dobriyal",
                    "Abhishek Banerjee"
                ],
                "characters": [
                    "Bhaskar Sharma",
                    "Ankita",
                    "Panda",
                    "Janardan"
                ],
                "slug": "https://www.jiocinema.com/movies/bhediya/3754021/watch",
                "assetRef": {},
                "telecastDate": "20230524",
                "releaseYear": 2022,
                "contentDescriptor": "Fantasy, Supernatural, Mild violence",
                "contentSubject": "",
                "age": "U/A 13+",
                "ageNumeric": 13,
                "ageNemonic": "13+",
                "ageDisplay": "U/A 13+",
                "name": "Bhediya",
                "duration": 8500,
                "durationFormatted": "2h 22m",
                "seo": {
                    "page": "Bhediya",
                    "title": "Bhediya (2022) Hindi Movie: Watch Full HD Movie Online On JioCinema",
                    "urlStructure": "https://www.jiocinema.com/movies/bhediya/3754021/watch",
                    "urlStructureNew": "https://www.jiocinema.com/movies/bhediya/3754021/watch",
                    "description": "Bhediya (2022) Is A Comedy Hindi Film Starring Varun Dhawan,Kriti Sanon,Deepak Dobriyal,Abhishek Banerjee In The Lead Roles, Directed By Amar Kaushik. Watch Now Or Download To Watch Later!",
                    "keywords": [
                        "Bhediya",
                        "Bhediya 2022 Online",
                        "Watch Hindi Movie Bhediya online",
                        "Watch Bhediya 2022",
                        "Bhediya HD Streaming Online",
                        "Bhediya videos",
                        "Bhediya",
                        "varun dhawan",
                        "kriti sanon",
                        "drama",
                        "thriller",
                        "action",
                        "love"
                    ],
                    "ogTitle": "Bhediya (2022) Hindi Movie: Watch Full HD Movie Online On JioCinema",
                    "ogDescription": "Bhediya (2022) Is A Comedy Hindi Film Starring Varun Dhawan,Kriti Sanon,Deepak Dobriyal,Abhishek Banerjee In The Lead Roles, Directed By Amar Kaushik. Watch Now Or Download To Watch Later!",
                    "ogImage": "https://v3img.voot.com/v3Storage/assets/3x4-1724140181377.jpg",
                    "imgTitle": "Bhediya",
                    "imgAltTags": "Watch Bhediya Online"
                },
                "introStart": 1,
                "introEnd": 102,
                "recapStart": 0,
                "recapEnd": 0,
                "creditStart": 8003,
                "creditEnd": 8500,
                "deeplinkUrl": "jiovootviacom18://jiovoot/detail/3754021",
                "shareUrl": "https://go.jc.fm/fRhd/2swsqndw",
                "shareUrlTabs": {},
                "shareUrlMessage": "Enjoy Bhediya on JioCinema. Click https://go.jc.fm/fRhd/2swsqndw now!",
                "jioMediaId": "3754021",
                "isDAIEnabled": false,
                "daiAssetKey": "",
                "isDVREnabled": false,
                "isHLSEnabled": false,
                "releaseDate": 1685026200,
                "uploadTime": 1685026200,
                "assetMarketType": "PREMIUM",
                "showMarketType": "PREMIUM",
                "assetBusinessType": [
                    "Premium"
                ]
            },
            {
                "id": "3502658",
                "mediaType": "MOVIE",
                "mediaSubType": "MOVIE",
                "downloadable": true,
                "languages": [
                    "Hindi"
                ],
                "defaultLanguage": "Hindi",
                "SBU": "CCP",
                "multiTrackAudioEnabled": false,
                "shortSynopsis": "Rajiv and Sanjana decide to come clean about their love to their families. Although Sanjana's don brothers agree, Rajiv's uncle becomes an obstacle, leading to hilarious ",
                "fullSynopsis": "Rajiv and Sanjana decide to come clean about their love to their families. Although Sanjana's don brothers agree, Rajiv's uncle becomes an obstacle, leading to hilarious decisions. Watch the movie, Welcome, on Jio Cinema!",
                "shortTitle": "Welcome",
                "fullTitle": "Welcome",
                "line1": "Welcome",
                "line2": "Hindi ∙ Comedy ∙ U/A 7+",
                "line3": "",
                "showId": "",
                "showName": "",
                "seasonId": "",
                "seasonName": "",
                "season": "",
                "seasonDisplay": "",
                "sampledCount": 0,
                "episode": "",
                "genres": [
                    "Comedy"
                ],
                "subGenre": [],
                "contributors": [
                    "Akshay Kumar",
                    " Katrina Kaif",
                    " Nana Patekar",
                    " Anil Kapoor",
                    " Paresh Rawal",
                    " Feroz Khan",
                    " Govardhan Asrani",
                    " Mallika Sherawat",
                    " Supriya Karnik",
                    " Sanjay Mishra",
                    " Paresh Ganatra",
                    " Malaika Arora"
                ],
                "characters": [
                    ""
                ],
                "slug": "https://www.jiocinema.com/movies/welcome/3502658/watch",
                "assetRef": {},
                "telecastDate": "20221102",
                "releaseYear": 2007,
                "contentDescriptor": "Family viewing, Comic mischief",
                "contentSubject": "",
                "age": "U/A 7+",
                "ageNumeric": 7,
                "ageNemonic": "7+",
                "ageDisplay": "U/A 7+",
                "name": "Welcome",
                "duration": 9093,
                "durationFormatted": "2h 32m",
                "seo": {
                    "page": "Welcome",
                    "title": "Welcome (2007) Hindi Movie: Watch Full HD Movie Online On JioCinema",
                    "urlStructure": "https://www.jiocinema.com/movies/welcome/3502658/watch",
                    "urlStructureNew": "https://www.jiocinema.com/movies/welcome/3502658/watch",
                    "description": "Welcome (2007) Is A Comedy Hindi Film Starring Akshay Kumar, Katrina Kaif, Nana Patekar, Anil Kapoor, Paresh Rawal, Feroz Khan, Govardhan Asrani, Mallika Sherawat, Supriya Karnik, Sanjay Mishra, Paresh Ganatra, Malaika Arora In The Lead Roles, Directed By Anees Bazmee. Watch Now Or Download To Watch Later!",
                    "keywords": [
                        "Welcome",
                        "Welcome 2007 Online",
                        "Watch Hindi Movie Welcome online",
                        "Watch Welcome 2007",
                        "Welcome HD Streaming Online",
                        "Welcome videos",
                        "Welcome",
                        "Welcome 2007",
                        "Hindi",
                        "Voot Hindi",
                        "Bollywood",
                        "Rajiv",
                        "Sanjana",
                        "Comedy",
                        "Anees Bazmee",
                        "Akshay Kumar",
                        "Katrina Kaif",
                        "Nana Patekar",
                        "Anil Kapoor",
                        "Feroz Khan",
                        "Mallika Sherawat",
                        "Paresh Rawal",
                        "Sunil Shetty"
                    ],
                    "ogTitle": "Welcome (2007) Hindi Movie: Watch Full HD Movie Online On JioCinema",
                    "ogDescription": "Welcome (2007) Is A Comedy Hindi Film Starring Akshay Kumar, Katrina Kaif, Nana Patekar, Anil Kapoor, Paresh Rawal, Feroz Khan, Govardhan Asrani, Mallika Sherawat, Supriya Karnik, Sanjay Mishra, Paresh Ganatra, Malaika Arora In The Lead Roles, Directed By Anees Bazmee. Watch Now Or Download To Watch Later!",
                    "ogImage": "https://v3img.voot.com/v3Storage/assets/welcome-1692953031837.jpg",
                    "imgTitle": "Welcome",
                    "imgAltTags": "Watch Welcome Online"
                }
            },
            {
                "id": "3492801",
                "mediaType": "MOVIE",
                "mediaSubType": "MOVIE",
                "downloadable": true,
                "languages": [
                    "Hindi"
                ],
                "defaultLanguage": "Hindi",
                "SBU": "X_ERN",
                "multiTrackAudioEnabled": false,
                "shortSynopsis": "Pritam, a single father, comes across his college sweetheart, Geeta, in Goa. However, the duo is left shocked to learn that their respective children cannot stand each ot",
                "fullSynopsis": "Pritam, a single father, comes across his college sweetheart, Geeta, in Goa. However, the duo is left shocked to learn that their respective children cannot stand each other! With a family that hate each other, can Pritam and Geeta ever reunite?",
                "shortTitle": "Golmaal 3",
                "fullTitle": "Golmaal 3",
                "line1": "Golmaal 3",
                "line2": "Hindi ∙ Comedy ∙ U/A 13+",
                "line3": "",
                "showId": "",
                "showName": "",
                "seasonId": "",
                "seasonName": "",
                "season": "",
                "seasonDisplay": "",
                "sampledCount": 0,
                "episode": "",
                "genres": [
                    "Comedy"
                ],
                "subGenre": [],
                "contributors": [
                    "Mithun Chakraborty",
                    "Arshad Warsi",
                    "Kunal Khemu",
                    "Tusshar Kapoor",
                    "Ratna Pathak",
                    "Ajay Devgan",
                    "Shreyas Talpade",
                    "Kareena Kapoor Khan",
                    "Johnny Lever"
                ],
                "characters": [
                    ""
                ],
                "slug": "https://www.jiocinema.com/movies/golmaal-3/3492801/watch",
                "assetRef": {},
                "telecastDate": "20210618",
                "releaseYear": 2010,
                "contentDescriptor": "Mild language,Mild violence",
                "contentSubject": "",
                "age": "U/A 13+",
                "ageNumeric": 13,
                "ageNemonic": "13+",
                "ageDisplay": "U/A 13+",
                "name": "Golmaal 3",
                "duration": 8060,
                "durationFormatted": "2h 14m",
                "seo": {
                    "page": "Golmaal 3",
                    "title": "Golmaal 3 (2010) Hindi Movie: Watch Full HD Movie Online On JioCinema",
                    "urlStructure": "https://www.jiocinema.com/movies/golmaal-3/3492801/watch",
                    "urlStructureNew": "https://www.jiocinema.com/movies/golmaal-3/3492801/watch",
                    "description": "Golmaal 3 (2010) Is A Comedy Hindi Film Starring Mithun Chakraborty,Arshad Warsi,Kunal Khemu,Tusshar Kapoor,Ratna Pathak,Ajay Devgan,Shreyas Talpade,Kareena Kapoor Khan,Johnny Lever In The Lead Roles, Directed By Rohit Shetty. Watch Now Or Download To Watch Later!",
                    "keywords": [
                        "Golmaal 3",
                        "Golmaal 3 2010 Online",
                        "Watch Hindi Movie Golmaal 3 online",
                        "Watch Golmaal 3 2010",
                        "Golmaal 3 HD Streaming Online",
                        "Golmaal 3 videos",
                        "Golmaal 3",
                        "Comedy",
                        "Ajay Devgn",
                        "Arshad Warsi",
                        "Tusshar Kapoor",
                        "Kunal Khemu",
                        "Shreyas Talpade",
                        "Kareena Kapoor",
                        "Johnny Lever",
                        "Ratna Pathak Shah",
                        "Mithun Chakraborty",
                        "Pritam",
                        "Gopal",
                        "Madhav",
                        "Lucky",
                        "Laxman",
                        "Laxman",
                        "Daboo",
                        "Geeta",
                        "Necklace",
                        "Queen's Necklace",
                        "Goa",
                        "Steal",
                        "Theft",
                        "Robbery",
                        "Orphans",
                        "Goons",
                        "Comedy"
                    ],
                    "ogTitle": "Golmaal 3 (2010) Hindi Movie: Watch Full HD Movie Online On JioCinema",
                    "ogDescription": "Golmaal 3 (2010) Is A Comedy Hindi Film Starring Mithun Chakraborty,Arshad Warsi,Kunal Khemu,Tusshar Kapoor,Ratna Pathak,Ajay Devgan,Shreyas Talpade,Kareena Kapoor Khan,Johnny Lever In The Lead Roles, Directed By Rohit Shetty. Watch Now Or Download To Watch Later!",
                    "ogImage": "https://v3img.voot.com/v3Storage/assets/golmaal_3_3x4-1696869682101.jpg",
                    "imgTitle": "Golmaal 3",
                    "imgAltTags": "Watch Golmaal 3 Online"
                }
            }
        ]
    }
]